# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmZhN2QzYWM0ZWUxMjIxNDg3YTkzMGQwNjMzYzk1YzY0MWU4YTJmMGRmMGU3MGJhN2Q0MThjYzYxMDFhNGNlZDkyYmZiMmJiMmI0NTljMjA2NzgwM2NjZTZmZDgyOWViNzJhOTljNGM0NzZhYTFjODk3NDQ2YWI2MzY2OWM3OTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
